import "./globals.css";
import { Logo } from "./components/logo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cyan-950 lg:w-3/4 mx-auto">
        <Logo />
        {children}
      </body>
    </html>
  );
}
